import React, { useEffect, useState } from 'react';
import { profileApi } from '../api/profile.api';
import { UploadedDocument } from '../types/document.types';
import { UserCircle, ShieldCheck, FileText } from 'lucide-react';
interface CitizenProfile { name:string;email:string;phone?:string;dateOfBirth?:string;registrationNumber?:string;college?:string;gender?:string;address?:string;district?:string;state?:string;pincode?:string;education?:string;category?:string;isVerified:boolean }
export const ProfilePage: React.FC = () => {
  const [data,setData]=useState<{profile:CitizenProfile;applicationCount:number}>(); const [documents,setDocuments]=useState<UploadedDocument[]>([]);
  useEffect(()=>{profileApi.get().then(setData);profileApi.documents().then(setDocuments)},[]); if(!data)return <p className="p-12 text-center">Loading profile…</p>;
  const fields=[['Mobile',data.profile.phone],['Date of birth',data.profile.dateOfBirth],['Gender',data.profile.gender],['College',data.profile.college],['Education',data.profile.education],['Category',data.profile.category],['Address',data.profile.address],['District',data.profile.district],['State',data.profile.state],['PIN code',data.profile.pincode],['Citizen reference',data.profile.registrationNumber],['Account status',data.profile.isVerified?'Verified':'Verification pending']];
  return <div className="max-w-4xl mx-auto px-6 py-10"><h1 className="text-3xl font-bold">Citizen Profile</h1><div className="grid md:grid-cols-[1fr_280px] gap-6 mt-6"><section className="bg-white border rounded-xl p-6"><div className="flex gap-4 items-center"><UserCircle size={54} className="text-gov-blue"/><div><h2 className="text-xl font-bold">{data.profile.name}</h2><p className="text-slate-500">{data.profile.email}</p></div></div><dl className="grid sm:grid-cols-2 gap-5 mt-7">{fields.map(([label,value])=><div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="font-semibold mt-1">{value||'Not provided'}</dd></div>)}</dl></section><aside className="bg-gov-blue text-white rounded-xl p-6"><ShieldCheck size={34}/><p className="text-3xl font-bold mt-5">{data.applicationCount}</p><p className="text-sm">Employment applications</p></aside></div><section className="bg-white border rounded-xl p-6 mt-6"><h2 className="text-xl font-bold">My Documents</h2><p className="text-sm text-slate-500">Only documents associated with your authenticated account are shown.</p><div className="divide-y mt-4">{documents.map(document=><a key={document._id} href={document.cloudinarySecureUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 py-3 text-sm text-gov-blue"><FileText size={18}/><span><strong>{document.documentType}</strong> — {document.originalFileName}</span></a>)}{!documents.length&&<p className="py-5 text-sm text-slate-500">No uploaded documents.</p>}</div></section></div>;
};
